/**
 * translate-to-en.mjs
 *
 * Comprehensive Russian-to-English translation script for the AIS Digital Waste Registry
 * Reads ru.json, translates every string value using a massive dictionary + pattern fallbacks,
 * and writes en.json preserving the exact JSON structure.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { supplementDict } from './dict-supplement.mjs';
import { supplementDict2 } from './dict-supplement2.mjs';
import { supplementDict3 } from './dict-supplement3.mjs';
import { supplementDict4 } from './dict-supplement4.mjs';
import { supplementDict5 } from './dict-supplement5.mjs';
import { supplementDict6 } from './dict-supplement6.mjs';
import { supplementDict7 } from './dict-supplement7.mjs';
import { supplementDict8 } from './dict-supplement8.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const INPUT = resolve(__dirname, '../src/locales/ru.json');
const OUTPUT = resolve(__dirname, '../src/locales/en.json');

// ============================================================
// 1. EXACT MATCH DICTIONARY (highest priority)
// ============================================================
const exactDict = {
  // ---- Common actions ----
  "Сохранить": "Save",
  "Отмена": "Cancel",
  "Удалить": "Delete",
  "Редактировать": "Edit",
  "Создать": "Create",
  "Подать": "Submit",
  "Отправить": "Send",
  "Скачать": "Download",
  "Экспорт": "Export",
  "Импорт": "Import",
  "Назад": "Back",
  "Закрыть": "Close",
  "Поиск": "Search",
  "Фильтр": "Filter",
  "Сбросить": "Reset",
  "Повторить": "Retry",
  "Выйти": "Log out",
  "Применить": "Apply",
  "Подтвердить": "Confirm",
  "Добавить": "Add",
  "Просмотреть": "View",
  "Печать": "Print",
  "Подробнее": "Details",
  "Все": "All",
  "Да": "Yes",
  "Нет": "No",
  "Загрузка...": "Loading...",
  "Нет данных": "No data",
  "Действия": "Actions",
  "Статус": "Status",
  "Дата": "Date",
  "Период": "Period",
  "Итого": "Total",
  "Сумма": "Amount",
  "Номер": "Number",
  "Наименование": "Name",
  "Описание": "Description",
  "Тип": "Type",
  "Регион": "Region",
  "Все регионы": "All regions",
  "С": "From",
  "По": "To",
  "С даты": "From date",
  "По дату": "To date",
  "Период с": "Period from",
  "Период по": "Period to",
  "Показано": "Shown",
  "из": "of",
  "записей": "records",
  "Далее": "Next",
  "Перейти к содержимому": "Skip to content",
  "Основная навигация": "Main navigation",
  "Меню": "Menu",
  "Открыть меню": "Open menu",
  "Выйти из системы": "Log out of system",
  "Главная": "Home",
  "Excel": "Excel",
  "PDF": "PDF",
  "Сформировать": "Generate",
  "Формирование...": "Generating...",
  "Параметры отчёта": "Report parameters",
  "Найдено": "Found",
  "объектов": "objects",
  "сом": "KGS",
  "дн.": "days",
  "т": "t",
  "шт": "pcs",
  "%": "%",
  "Назад к списку": "Back to list",
  "Сохранить черновик": "Save draft",
  "Добавить строку": "Add row",
  "Отправить отчёт": "Submit report",
  "Создать отчёт": "Create report",
  "Скачать Excel": "Download Excel",
  "Скачать PDF": "Download PDF",
  "Скачать отчёт Excel": "Download report (Excel)",
  "Скачать отчёт PDF": "Download report (PDF)",
  "Выгрузить отчёт": "Export report",
  "Выгрузить данные": "Export data",
  "Детали": "Details",
  "Принять": "Accept",
  "Отклонить": "Reject",
  "Успешно": "Success",
  "Просмотр": "Preview",
  "ГП Эко Оператор": "SE Eco Operator",
  "ГП «Эко Оператор»": "SE \"Eco Operator\"",
  "Государственное предприятие": "State Enterprise",
  "Пн-Пт: 9:00 - 18:00": "Mon-Fri: 9:00 AM - 6:00 PM",
  "Сб-Вс: выходной": "Sat-Sun: Day off",
  "г. Бишкек": "Bishkek",
  "ул. Токтогула, 228": "228 Toktogul St.",
  "г. Бишкек, ул. Токтогула, 228": "228 Toktogul St., Bishkek",
  "720040, г. Бишкек": "720040, Bishkek",
  "Все статусы": "All statuses",

  // ---- Roles ----
  "Плательщик": "Payer",
  "Сотрудник МПРЭТН КР": "MNRE KR Employee",
  "Администратор": "Administrator",

  // ---- Navigation ----
  "О портале": "About",
  "Законодательство": "Legislation",
  "Лицензии": "Licenses",
  "Публикации": "Publications",
  "ГИС-Карта": "GIS Map",
  "Калькулятор РОП": "EPR Calculator",
  "Конкурсы": "Contests",
  "Реестры": "Registries",
  "Глоссарий": "Glossary",
  "Регистрация": "Registration",
  "Войти": "Sign in",
  "Расчёт утильсбора": "Recycling fee calculation",
  "Отчёты о переработке": "Recycling reports",
  "Декларации": "Declarations",
  "Платежи": "Payments",
  "Документы": "Documents",
  "Нормативы и ставки": "Standards and rates",
  "Лицевой счёт": "Account statement",
  "Возврат утильсбора": "Recycling fee refund",
  "Профиль компании": "Company profile",
  "Организации": "Organizations",
  "Входящие декларации": "Incoming declarations",
  "Входящие расчёты": "Incoming calculations",
  "Реестр переработчиков": "Recyclers registry",
  "Полигоны ТБО": "Landfills",
  "Аналитика и отчёты": "Analytics and reports",
  "Лицевые счета": "Account statements",
  "Заявки на возврат": "Refund applications",
  "Реестр плательщиков": "Payers registry",
  "Профили компаний": "Company profiles",
  "Аналитика": "Analytics",
  "Контроль исполнения": "Compliance monitoring",
  "Виды отходов": "Waste types",
  "Полигоны и свалки": "Landfills and dumps",
  "Пункты приёма": "Reception points",
  "Отчётность": "Reporting",
  "ГИС-карта": "GIS Map",
  "Мой профиль": "My profile",
  "Пользователи": "Users",
  "Роли и права": "Roles and permissions",
  "Справочники": "References",
  "Журнал аудита": "Audit log",
  "Уведомления": "Notifications",
  "Настройки системы": "System settings",

  // ---- Statuses ----
  "Черновик": "Draft",
  "На проверке": "Under review",
  "На рассмотрении": "Under consideration",
  "Принято": "Accepted",
  "Принят": "Accepted",
  "Одобрена": "Approved",
  "Отклонено": "Rejected",
  "Отклонён": "Rejected",
  "Отклонена": "Rejected",
  "Оплачено": "Paid",
  "Оплата на проверке": "Payment under review",
  "Оплата отклонена": "Payment rejected",
  "На доработке": "Under revision",
  "Новая": "New",
  "Новый": "New",
  "Действует": "Active",
  "Истекает": "Expiring",
  "Истекла": "Expired",
  "Аннулирован": "Revoked",
  "Аннулирована": "Revoked",
  "Активен": "Active",
  "Активна": "Active",
  "Заблокирован": "Blocked",
  "Временно заблокирован": "Temporarily blocked",
  "Ожидает подтверждения": "Pending confirmation",
  "Деактивирован": "Deactivated",
  "Деактивирована": "Deactivated",
  "Приостановлен": "Suspended",
  "Приостановлена": "Suspended",
  "Закрыт": "Closed",
  "Рекультивация": "Recultivation",
  "Сбор оплачен": "Fee paid",
  "Пеня оплачена": "Penalty paid",
  "Принята": "Accepted",
  "Подана": "Submitted",
  "Подан": "Submitted",
  "Отправлен": "Sent",
  "Отправлена": "Sent",
  "В обработке": "Processing",
  "В работе": "In progress",
  "Завершён": "Completed",
  "Завершена": "Completed",
  "Отменено": "Cancelled",
  "Отменена": "Cancelled",
  "Неактивен": "Inactive",
  "Неактивна": "Inactive",
  "Выполнен": "Fulfilled",
  "Близко к норме": "Close to norm",
  "Не выполнен": "Not fulfilled",
  "Частично": "Partial",
  "Хорошее": "Good",
  "Требует внимания": "Needs attention",
  "Критическое": "Critical",
  "Соответствует": "Compliant",
  "Нарушения": "Non-compliant",
  "Оплачена": "Paid",
  "Проведён": "Completed",
  "Исключён": "Excluded",

  // ---- Validation ----
  "ИНН должен содержать 14 цифр": "TIN must contain 14 digits",
  "Некорректный email": "Invalid email",
  "Формат: +996 XXX XXX XXX": "Format: +996 XXX XXX XXX",
  "Выберите отчётный период": "Select reporting period",
  "Добавьте хотя бы одну позицию": "Add at least one item",
  "Заполните все обязательные поля в позициях": "Fill in all required fields in items",
  "Укажите отчётный год": "Specify reporting year",

  // ---- Empty states ----
  "У вас пока нет расчётов": "You have no calculations yet",
  "Подайте первый расчёт утилизационного сбора": "Submit your first recycling fee calculation",
  "Нет новых расчётов на проверку": "No new calculations to review",
  "Когда организации подадут расчёты, они появятся здесь": "When organizations submit calculations, they will appear here",
  "Нет новых уведомлений": "No new notifications",
  "По запросу ничего не найдено": "Nothing found for your query",
  "Попробуйте изменить параметры фильтрации или поисковый запрос": "Try changing filter parameters or search query",
  "Сбросить фильтры": "Reset filters",
  "Нет деклараций": "No declarations",
  "Подайте первую декларацию для начала работы": "Submit your first declaration to get started",
  "Нет платежей": "No payments",
  "Платежи появятся после подачи расчётов": "Payments will appear after submitting calculations",
  "Нет документов": "No documents",
  "Загруженные документы появятся здесь": "Uploaded documents will appear here",
  "Нет отчётов": "No reports",
  "Создайте первый отчёт о переработке": "Create your first recycling report",
  "Нет заявок на возврат": "No refund applications",
  "Здесь будут отображаться заявки на возврат утильсбора": "Recycling fee refund applications will be displayed here",
  "Нет организаций": "No organizations",
  "Нет лицензий": "No licenses",
  "Нет данных по нормативам": "No standards data",
  "Данные о нормативах переработки за текущий период пока отсутствуют": "Recycling standards data for the current period is not yet available",
  "Нет данных по лицензиям": "No license data",
  "Данные о лицензиях и разрешениях пока отсутствуют": "License and permit data is not yet available",
  "Нет полигонов": "No landfills",
  "Нет полигонов, соответствующих выбранным фильтрам": "No landfills matching the selected filters",
  "Нет лицензий, соответствующих выбранным фильтрам": "No licenses matching the selected filters",
  "Нет лицевых счетов": "No account statements",
  "Нет записей в журнале аудита": "No audit log entries",

  // ---- Errors ----
  "Произошла ошибка при загрузке данных": "An error occurred while loading data",
  "Непредвиденная ошибка": "Unexpected error",
  "Ошибка сети. Проверьте подключение к интернету": "Network error. Check your internet connection",
  "Доступ запрещён": "Access denied",
  "Ошибка сервера": "Server error",
  "Ошибка API": "API error",
  "Ошибка авторизации": "Authorization error",
  "Ошибка регистрации": "Registration error",

  // ---- Not found ----
  "Страница не найдена": "Page not found",
  "Запрашиваемая страница не существует или была перемещена": "The requested page does not exist or has been moved",
  "На главную": "Go home",

  // ---- Notifications ----
  "Прочитать все": "Read all",
  "Нет уведомлений": "No notifications",
  "Все уведомления": "All notifications",
  "Перейти": "Go to",
  "Непрочитанные": "Unread",
  "Удалить все прочитанные": "Delete all read",
  "Нет непрочитанных уведомлений": "No unread notifications",
  "Управление уведомлениями": "Notification management",

  // ---- Timeline ----
  "Создан": "Created",
  "Счёт": "Invoice",
  "Оплачен": "Paid",
  "Исправить": "Fix",

  // ---- Dashboard ----
  "Панель управления": "Dashboard",
  "Обзор текущих данных и задач": "Overview of current data and tasks",

  // ---- Pages (Business) ----
  "Расчёт утилизационного сбора": "Recycling fee calculation",
  "Рассчитайте сумму утилизационного сбора по товарным группам": "Calculate the recycling fee by product groups",
  "Подача и отслеживание отчётов о переработке отходов": "Submission and tracking of waste recycling reports",
  "Подача и просмотр деклараций об утилизационном сборе": "Submission and viewing of recycling fee declarations",
  "История и статусы платежей по утилизационному сбору": "Payment history and statuses for recycling fees",
  "Загрузка и управление подтверждающими документами": "Upload and manage supporting documents",
  "Актуальные нормативы переработки и ставки утильсбора": "Current recycling standards and fee rates",
  "Баланс, начисления и платежи по лицевому счёту": "Balance, charges, and payments on account statement",
  "Подача и отслеживание заявок на возврат": "Submission and tracking of refund applications",
  "Данные организации и контактная информация": "Organization data and contact information",

  // ---- Pages (Eco Operator) ----
  "Обзор входящих расчётов и задач оператора": "Overview of incoming calculations and operator tasks",
  "Реестр зарегистрированных организаций": "Registry of registered organizations",
  "Проверка и обработка деклараций от организаций": "Review and processing of declarations from organizations",
  "Входящие отчёты о переработке": "Incoming recycling reports",
  "Проверка отчётов о выполнении нормативов переработки": "Review of recycling standards compliance reports",
  "Проверка и обработка расчётов утилизационного сбора": "Review and processing of recycling fee calculations",
  "Лицензированные организации по переработке отходов": "Licensed waste recycling organizations",
  "Реестр полигонов и объектов размещения отходов": "Registry of landfills and waste disposal facilities",
  "Сводная аналитика и формирование отчётов": "Summary analytics and report generation",
  "Управление лицевыми счетами организаций": "Organization account statement management",
  "Рассмотрение заявок на возврат утильсбора": "Review of recycling fee refund applications",
  "Управление профилями организаций": "Organization profile management",
  "Моё предприятие": "My enterprise",
  "Данные предприятия и контактная информация": "Enterprise data and contact information",
  "Перечень принимаемых и перерабатываемых отходов": "List of accepted and recycled waste types",
  "Аналитика платежей": "Payment analytics",
  "Поступления утилизационного сбора и задолженности": "Recycling fee receipts and arrears",
  "Мои отчёты": "My reports",
  "Отчётность о переработке отходов": "Waste recycling reporting",
  "Лицензии и документы": "Licenses and documents",
  "Управление разрешительной документацией": "Permit documentation management",

  // ---- Pages (Employee) ----
  "Обзор задач и показателей": "Overview of tasks and indicators",
  "Мониторинг выполнения нормативов переработки и контроль лицензий": "Monitoring recycling standards compliance and license control",
  "Реестр выданных лицензий и контроль сроков": "Registry of issued licenses and deadline control",
  "Классификация и характеристики видов отходов": "Classification and characteristics of waste types",
  "Мониторинг состояния полигонов и свалок": "Monitoring landfill and dump conditions",
  "Формирование и выгрузка отчётов для МПРЭТН": "Report generation and export for MNRE",
  "Интерактивная карта объектов обращения с отходами": "Interactive map of waste management facilities",
  "Персональные данные и настройки": "Personal data and settings",

  // ---- Pages (Admin) ----
  "Обзор состояния системы": "System status overview",
  "Управление учётными записями пользователей": "User account management",
  "Настройка ролей и прав доступа": "Role and access permission settings",
  "Управление справочными данными системы": "System reference data management",
  "Аудит всех операций в системе": "Audit of all system operations",
  "Управление шаблонами уведомлений": "Notification template management",
  "Конфигурация параметров системы": "System parameter configuration",

  // ---- Login ----
  "ВХОД В СИСТЕМУ": "SIGN IN",
  "Авторизация по ИНН и паролю": "Authorization by TIN and password",
  "Войти через ЕСИ Тундук": "Sign in via ESI Tunduk",
  "или": "or",
  "Вход по ИНН и паролю": "Sign in by TIN and password",
  "ИНН организации": "Organization TIN",
  "Введите ИНН": "Enter TIN",
  "Пароль": "Password",
  "Введите пароль": "Enter password",
  "Нет аккаунта?": "No account?",
  "Зарегистрироваться": "Register",
  "Забыли пароль?": "Forgot password?",
  "Неверный ИНН или пароль": "Invalid TIN or password",
  "Заполните все поля": "Fill in all fields",
  "Подключение к ЕСИ Түндүк...": "Connecting to ESI Tunduk...",
  "Перенаправление на страницу авторизации": "Redirecting to authorization page",
  "Демо-режим (бэкенд недоступен)": "Demo mode (backend unavailable)",

  // ---- Registration ----
  "Регистрация плательщика утилизационного сбора": "Recycling fee payer registration",
  "Выберите способ регистрации": "Choose registration method",
  "Зарегистрироваться через ЕСИ Түндүк": "Register via ESI Tunduk",
  "Быстрая регистрация — данные будут заполнены автоматически из ЕСИ": "Quick registration - data will be filled automatically from ESI",
  "Зарегистрироваться без ЕСИ (заполнить вручную)": "Register without ESI (fill in manually)",
  "Уже есть аккаунт?": "Already have an account?",
  "Получение данных организации": "Retrieving organization data",
  "Регистрация через ЕСИ Түндүк": "Registration via ESI Tunduk",
  "Проверьте данные и заполните дополнительную информацию": "Check data and fill in additional information",
  "Данные из ЕСИ Түндүк": "Data from ESI Tunduk",
  "Подтверждено": "Confirmed",
  "ИНН": "TIN",
  "ФИО руководителя": "Director's full name",
  "Юридический адрес": "Legal address",
  "Телефон": "Phone",
  "Email": "Email",
  "Дополнительная информация": "Additional information",
  "Вид деятельности": "Activity type",
  "Категории товаров (группы отходов)": "Product categories (waste groups)",
  "24 группы продукции (ПКМ КР №322)": "24 product groups (GD KR No. 322)",
  "Выбрать все": "Select all",
  "Снять все": "Deselect all",
  "Мощности переработки (т/год)": "Recycling capacity (t/year)",
  "т/год": "t/year",
  "Отправка...": "Sending...",
  "Отправить заявку на регистрацию": "Submit registration application",
  "Заявка на регистрацию отправлена!": "Registration application submitted!",
  "Номер заявки": "Application number",
  "Вернуться на главную": "Return to home page",
  "Фамилия": "Last name",
  "Имя": "First name",
  "Отчество": "Middle name",
  "Серия паспорта": "Passport series",
  "Номер паспорта": "Passport number",
  "Кем выдан": "Issued by",
  "Дата выдачи": "Issue date",
  "Краткое наименование": "Short name",
  "Полное наименование": "Full name",
  "ИНН (14 цифр)": "TIN (14 digits)",
  "ОКПО": "OKPO",
  "ВИДЫ ПРОДУКЦИИ": "PRODUCT TYPES",
  "Выбрано": "Selected",
  "групп": "groups",
  "Область/город": "Region/city",
  "Город/район": "City/district",
  "Улица": "Street",
  "Дом/офис": "Building/office",
  "Фактический адрес": "Actual address",
  "Совпадает с юридическим": "Same as legal address",
  "Выберите": "Select",
  "Контактный телефон": "Contact phone",
  "Руководитель и контактное лицо": "Director and contact person",
  "Руководитель организации": "Organization director",
  "ФИО": "Full name",
  "Должность": "Position",
  "Контактное лицо": "Contact person",
  "Загрузка документов": "Document upload",
  "PDF, JPG, PNG до 10 МБ": "PDF, JPG, PNG up to 10 MB",
  "Выбрать файл": "Choose file",
  "Файл не загружен": "File not uploaded",
  "Перетащите файлы сюда": "Drag files here",
  "Руководитель": "Director",
  "Примечание": "Note",
  "Прикреплённые документы": "Attached documents",
  "Документы не прикреплены": "No documents attached",
  "Паспорт": "Passport",

  // ---- Registration steps ----
  "Тип организации": "Organization type",
  "Данные организации": "Organization data",
  "Руководитель и контакты": "Director and contacts",
  "Проверка и отправка": "Review and submit",

  // ---- Organization types ----
  "Хозяйственные общества": "Business entities",
  "Государственные и муниципальные": "State and municipal",
  "Кооперативы и товарищества": "Cooperatives and partnerships",
  "Некоммерческие": "Non-commercial",
  "Индивидуальные": "Individual",
  "Иностранные": "Foreign",
  "ОсОО (Общество с ограниченной ответственностью)": "LLC (Limited Liability Company)",
  "ОАО (Открытое акционерное общество)": "OJSC (Open Joint-Stock Company)",
  "ЗАО (Закрытое акционерное общество)": "CJSC (Closed Joint-Stock Company)",
  "ОДО (Общество с дополнительной ответственностью)": "ALC (Additional Liability Company)",
  "ГП (Государственное предприятие)": "SE (State Enterprise)",
  "МП (Муниципальное предприятие)": "ME (Municipal Enterprise)",
  "ПК (Производственный кооператив)": "PC (Production Cooperative)",
  "Полное товарищество": "General Partnership",
  "Коммандитное товарищество": "Limited Partnership",
  "ОО (Общественное объединение)": "PA (Public Association)",
  "ОФ (Общественный фонд)": "PF (Public Fund)",
  "Учреждение": "Institution",
  "ИП (Индивидуальный предприниматель)": "IE (Individual Entrepreneur)",
  "КФХ (Крестьянское (фермерское) хозяйство)": "FH (Farm Household)",
  "Филиал иностранного юридического лица": "Branch of foreign legal entity",
  "Представительство иностранного юридического лица": "Representative office of foreign legal entity",

  // ---- Activity types ----
  "Импортёр": "Importer",
  "Производитель": "Producer",
  "Импортёр и Производитель": "Importer and Producer",
  "Переработчик отходов": "Waste recycler",
  "Импортер": "Importer",
  "Импортер и производитель": "Importer and producer",

  // ---- File categories ----
  "Свидетельство о регистрации": "Registration certificate",
  "Выписка из реестра": "Registry extract",
  "Лицензия (если есть)": "License (if available)",
  "Доверенность (если регистрирует не руководитель)": "Power of attorney (if not registered by director)",

  // ---- Time ----
  "только что": "just now",

  // ---- UI ----
  "— Выберите —": "— Select —",
  "Поиск...": "Search...",
  "Ничего не найдено": "Nothing found",
  "Выберите...": "Select...",

  // ---- Stub ----
  "Раздел в разработке": "Section under development",
  "Данный функционал будет доступен в ближайшее время": "This functionality will be available soon",

  // ---- Instruction ----
  "Инструкция по заполнению": "Filling instructions",
  "Показать подсказку": "Show hint",
  "✕ Скрыть подсказку": "✕ Hide hint",

  // ---- Document preview ----
  "Тип файла": "File type",
  "Размер": "Size",
  "Дата загрузки": "Upload date",
  "Предпросмотр содержимого будет доступен после подключения файлового хранилища": "Content preview will be available after connecting file storage",
  "Скачивание документа": "Document download",
  "Скачивание будет доступно после подключения файлового хранилища": "Download will be available after connecting file storage",

  // ---- Role selection ----
  "Вход в систему": "Sign in",
  "Выберите вашу роль для входа в личный кабинет": "Select your role to access the dashboard",
  "Управление системой": "System management",
  "Министерство природных ресурсов, экологии и технического надзора": "Ministry of Natural Resources, Ecology and Technical Supervision",
  "Импортёры, производители товаров и упаковки": "Importers, producers of goods and packaging",

  // ---- CTA ----
  "Присоединяйтесь к устойчивому развитию": "Join sustainable development",
  "Реестры участников": "Participant registries",
  "Калькулятор сборов": "Fee calculator",
  "Связаться с нами": "Contact us",

  // ---- Product group ----
  "Группа товара": "Product group",
  "Выберите группу": "Select group",
  "Подгруппа": "Subgroup",
  "Код ГСКП": "SCCP Code",
  "Код ТН ВЭД": "HS Code",
  "Наименование ТН ВЭД": "HS Code name",
  "Материал упаковки": "Packaging material",
  "Обозначение ТР ТС": "TR CU designation",
  "Код ТР ТС": "TR CU code",

  // ---- Document types ----
  "ГТД": "CCD",
  "Акт приёма-передачи": "Transfer and acceptance act",
  "Товарная накладная": "Goods invoice",
  "Инвойс": "Invoice",
  "Договор с переработчиком": "Contract with recycler",
  "Иное": "Other",

  // ---- Payer categories ----
  "Страны ЕАЭС": "EAEU countries",
  "Третьи страны": "Third countries",
  "Сдана вовремя": "Submitted on time",
  "Ожидается": "Expected",
  "Просрочена": "Overdue",
  "Без задолженности": "No debt",
  "Переплата": "Overpayment",
  "Задолженность": "Debt",

  // ---- Recycler ----
  "Соответствует требованиям": "Meets requirements",
  "Выявлены нарушения": "Violations found",
  "Требуется повторная проверка": "Re-inspection required",

  // ---- Months ----
  "Янв": "Jan",
  "Фев": "Feb",
  "Мар": "Mar",
  "Апр": "Apr",
  "Май": "May",
  "Июн": "Jun",
  "Июл": "Jul",
  "Авг": "Aug",
  "Сен": "Sep",
  "Окт": "Oct",
  "Ноя": "Nov",
  "Дек": "Dec",

  // ---- Audit actions ----
  "Создание": "Create",
  "Изменение": "Update",
  "Удаление": "Delete",
  "Вход": "Login",
  "Выход": "Logout",
  "Экспорт журнала": "Export log",
  "Всего записей": "Total records",
  "Успешных": "Successful",
  "Предупреждений": "Warnings",
  "Ошибок": "Errors",
  "Тип действия": "Action type",
  "Объект": "Object",
  "Все типы": "All types",
  "Все объекты": "All objects",
  "Время": "Time",
  "Пользователь": "User",
  "Действие": "Action",
  "IP адрес": "IP address",
  "ID записи": "Record ID",
  "Дата и время": "Date and time",
  "Роль": "Role",
  "ID объекта": "Object ID",
  "Подробности": "Details",
  "Предупреждение": "Warning",
  "Ошибка": "Error",
  "Админ": "Admin",
  "Сотрудник": "Employee",
  "Эко-оператор": "Eco-operator",
  "Система": "System",
  "Расчёты": "Calculations",

  // ---- Analytics ----
  "Аналитика системы": "System analytics",
  "Сводная статистика и показатели эффективности": "Summary statistics and performance indicators",
  "Месяц": "Month",
  "Квартал": "Quarter",
  "Год": "Year",
  "Всего собрано": "Total collected",
  "Переработано отходов": "Waste recycled",
  "Активных организаций": "Active organizations",
  "Выдано лицензий": "Licenses issued",
  "тонн": "tons",
  "vs прошлый год": "vs last year",
  "Динамика сборов по месяцам": "Monthly fee dynamics",
  "Факт": "Actual",
  "План": "Plan",
  "Структура по категориям": "Category breakdown",
  "млн": "mln",
  "млн сом": "mln KGS",
  "Сборы по регионам": "Revenue by region",
  "Показатели системы": "System metrics",
  "Всего пользователей": "Total users",
  "активных": "active",
  "Всего деклараций": "Total declarations",
  "Всего отчётов": "Total reports",
  "за всё время": "all time",
  "Среднее время обработки": "Average processing time",
  "дней": "days",
  "Аптайм системы": "System uptime",
  "Выполнение нормативов переработки (по стране)": "Recycling standards compliance (nationwide)",

  // ---- Eco Analytics ----
  "Общая сводка": "Summary",
  "Финансы": "Finance",
  "Товары и переработка": "Products and recycling",
  "Региональная статистика": "Regional statistics",
  "Выгрузка отчётов": "Report export",
  "Этот месяц": "This month",
  "Этот год": "This year",
  "Произвольный период": "Custom period",
  "Группа товаров": "Product group",
  "Все группы": "All groups",
  "Все подгруппы": "All subgroups",
  "Сбросить": "Reset",
  "Нет данных за выбранный период": "No data for selected period",
  "Плательщиков на учёте": "Registered payers",
  "Начислено утильсбора": "Recycling fee charged",
  "Собрано утильсбора": "Recycling fee collected",
  "Деклараций подано": "Declarations submitted",
  "Переработано (тонн)": "Recycled (tons)",
  "Динамика сбора утилизационного сбора": "Recycling fee collection dynamics",
  "Начислено": "Charged",
  "Собрано": "Collected",
  "Собираемость по регионам": "Collection rate by region",
  "Топ-5 должников": "Top 5 debtors",
  "Компания": "Company",
  "Просрочка": "Overdue",
  "Поступило от утильсбора": "Received from recycling fee",
  "Возвращено": "Returned",
  "Чистые поступления": "Net receipts",
  "Средний расчёт": "Average calculation",
  "Динамика поступлений": "Receipt dynamics",
  "По месяцам": "By months",
  "По кварталам": "By quarters",
  "Поступления": "Receipts",
  "Возвраты": "Refunds",
  "Структура поступлений": "Receipt structure",
  "По группам товаров": "By product groups",
  "По типу плательщиков": "By payer type",
  "Переработчики": "Recyclers",
  "Производители": "Producers",
  "Импортёры": "Importers",
  "Импортёры и производители": "Importers and producers",

  // ---- Calculator page ----
  "Калькулятор утилизационного сбора (РОП)": "Recycling Fee Calculator (EPR)",
  "Калькулятор сбора": "Fee calculator",
  "Калькулятор пени": "Penalty calculator",
  "Параметры расчёта": "Calculation parameters",
  "Тип операции": "Operation type",
  "Производство": "Production",
  "Год расчёта": "Calculation year",
  "Товары и упаковка": "Goods and packaging",
  "Позиция": "Item",
  "Удалить позицию": "Delete item",
  "Масса (тонн)": "Mass (tons)",
  "1 тонна = 1 000 кг": "1 ton = 1,000 kg",
  "Норматив переработки": "Recycling standard",
  "К переработке (т)": "To be recycled (t)",
  "Ставка (сом/т)": "Rate (KGS/t)",
  "Добавить ещё позицию": "Add another item",
  "Рассчитать": "Calculate",
  "Очистить": "Clear",
  "Результат расчёта": "Calculation result",
  "Группа": "Group",
  "Масса (т)": "Mass (t)",
  "Норм. (%)": "Norm. (%)",
  "К перер. (т)": "To recycle (t)",
  "Ставка": "Rate",
  "Сумма (сом)": "Amount (KGS)",
  "ИТОГО": "TOTAL",
  "Итого утилизационный сбор:": "Total recycling fee:",
  "Новый расчёт": "New calculation",
  "О калькуляторе": "About calculator",
  "Нормативы переработки по годам": "Recycling standards by year",
  "Введите числовое значение": "Enter a numeric value",
  "Объём должен быть больше 0": "Volume must be greater than 0",
  "Максимум 99 999 тонн": "Maximum 99,999 tons",
  "Окно заблокировано": "Window blocked",
  "Разрешите всплывающие окна для скачивания PDF": "Allow pop-ups to download PDF",

  // ---- Payment panel ----
  "Утилизационный сбор": "Recycling fee",
  "Пеня": "Penalty",
  "Оплата расчёта": "Calculation payment",
  "Не оплачено": "Not paid",
  "Реквизиты для оплаты": "Payment details",
  "Получатель": "Recipient",
  "Банк": "Bank",
  "Расчётный счёт": "Settlement account",
  "БИК": "BIC",
  "Скопировать реквизиты": "Copy payment details",
  "QR-код для мобильного банка": "QR code for mobile banking",
  "Загрузить квитанцию об оплате": "Upload payment receipt",
  "Отправить квитанцию": "Submit receipt",
  "Сумма сбора": "Fee amount",
  "Сумма пени": "Penalty amount",
  "Итого к оплате": "Total payable",
  "Загружено, ожидает подтверждения": "Uploaded, pending confirmation",
  "Оплата подтверждена": "Payment confirmed",
  "Сначала оплатите утилизационный сбор": "Pay the recycling fee first",
  "Свернуть": "Collapse",
  "Назначение платежа": "Payment purpose",
  "Открыть на отдельной странице": "Open on separate page",
  "после сбора": "after fee",
  "от суммы сбора": "of the fee amount",
  "ИТОГО К ОПЛАТЕ": "TOTAL PAYABLE",

  // ---- Waste materials ----
  "Пластик": "Plastic",
  "Бумага/картон": "Paper/cardboard",
  "Стекло": "Glass",
  "Металл": "Metal",
  "Текстиль": "Textile",
  "Шины": "Tires",
  "Бумага": "Paper",
  "Картон": "Cardboard",
  "Алюминий": "Aluminum",
  "Электроника": "Electronics",
  "Батарейки": "Batteries",
  "Батареи": "Batteries",

  // ---- Region names ----
  "г. Ош": "Osh",
  "Чуйская область": "Chui region",
  "Ошская область": "Osh region",
  "Джалал-Абадская область": "Jalal-Abad region",
  "Иссык-Кульская область": "Issyk-Kul region",
  "Нарынская область": "Naryn region",
  "Таласская область": "Talas region",
  "Баткенская область": "Batken region",
  "Бишкек": "Bishkek",
  "Ош": "Osh",

  // ---- Admin settings tabs ----
  "Общие": "General",
  "Безопасность": "Security",
  "Email уведомления": "Email notifications",
  "Интеграции": "Integrations",
  "Резервные копии": "Backups",
  "Обслуживание": "Maintenance",

  // ---- Security settings ----
  "Настройки безопасности": "Security settings",
  "Требования к паролю": "Password requirements",
  "Минимальная длина": "Minimum length",
  "Требовать заглавные буквы": "Require uppercase letters",
  "Требовать цифры": "Require digits",
  "Требовать спецсимволы": "Require special characters",
  "Обязательная двухфакторная аутентификация": "Mandatory two-factor authentication",

  // ---- Misc common ----
  "Инструкция": "Instructions",
  "Детализация": "Details",
  "Комментарий": "Comment",
  "Сохранение...": "Saving...",
  "Сохранить изменения": "Save changes",
  "Настроить": "Configure",
  "Включить": "Enable",
  "Отключить": "Disable",
  "Синхронизировать": "Synchronize",
  "Отключено": "Disabled",
  "Версия": "Version",
  "Память": "Memory",
  "База данных": "Database",
  "Готово": "Done",
  "Подтвердить": "Confirm",
  "Выполнение...": "Processing...",
  "Проверить обновления": "Check for updates",
  "Очистить кэш": "Clear cache",
  "Перезапустить очереди": "Restart queues",
  "Восстановить": "Restore",
  "Вы уверены, что хотите продолжить?": "Are you sure you want to continue?",
  "Веб-сайт": "Website",
  "Дата регистрации": "Registration date",
  "Общая мощность": "Total capacity",
  "Текущая загрузка": "Current load",
  "Загрузка": "Load",
  "Свободно": "Available",
  "Переработчик": "Recycler",
  "Верифицирован": "Verified",
  "Не верифицирован": "Not verified",
  "Заполненность профиля": "Profile completion",
  "Отлично! Все данные заполнены": "Great! All data is filled in",
  "Двухфакторная аутентификация": "Two-factor authentication",
  "Текущий пароль": "Current password",
  "Новый пароль": "New password",
  "Подтвердите пароль": "Confirm password",
  "Изменить пароль": "Change password",
  "Пароли не совпадают": "Passwords do not match",
  "Пароль успешно изменён": "Password changed successfully",
  "Активные сессии": "Active sessions",
  "Завершить": "Terminate",
  "Настройки уведомлений": "Notification settings",
  "Email-уведомления": "Email notifications",
  "SMS-уведомления": "SMS notifications",
  "Напоминания о декларациях": "Declaration reminders",
  "Напоминания об оплате": "Payment reminders",
  "Сроки отчётности": "Reporting deadlines",
  "Новости и обновления": "News and updates",
  "Изменение пароля": "Password change",
  "Дополнительная защита вашего аккаунта": "Additional protection for your account",
  "Банковские реквизиты": "Bank details",
  "Наименование банка": "Bank name",
  "Корреспондентский счёт": "Correspondent account",
  "Не указан": "Not specified",

  // ---- Landfill types ----
  "Санитарный полигон": "Sanitary landfill",
  "Несанкционированная свалка": "Unauthorized dump",
  "Мусоросортировочная станция": "Waste sorting station",
  "Несанкц. свалка": "Unauth. dump",
  "Действующий": "Active",
  "Закрыт": "Closed",
  "На рекультивации": "Under recultivation",
  "Заполненность:": "Fill level:",
  "Класс опасности:": "Hazard class:",
  "Список": "List",
  "Карта": "Map",
  "Добавить полигон": "Add landfill",
  "Легенда:": "Legend:",

  // ---- GIS Map ----
  "Полигоны ТБО": "Landfills",
  "Несанкц. свалки": "Unauthorized dumps",
  "Плательщики": "Payers",
  "Приблизить": "Zoom in",
  "Отдалить": "Zoom out",
  "Показать всю карту": "Show full map",
  "Где я": "Where am I",
  "Реестр объектов": "Object registry",

  // ---- License types ----
  "На сбор отходов": "For waste collection",
  "На транспортировку отходов": "For waste transportation",
  "На переработку (утилизацию) отходов": "For waste recycling (disposal)",
  "На обезвреживание отходов": "For waste neutralization",
  "На размещение (захоронение) отходов": "For waste placement (burial)",
  "Комплексная": "Complex",

  // ---- Recycling technologies ----
  "Механическая переработка": "Mechanical recycling",
  "Термическая переработка": "Thermal recycling",
  "Экструзия вторсырья": "Secondary material extrusion",
  "Прессование и пакетирование": "Pressing and baling",
  "Роспуск и прессование": "Dissolving and pressing",
  "Химическая переработка": "Chemical recycling",
  "Компостирование": "Composting",
  "Пиролиз": "Pyrolysis",
  "Измельчение (шредирование)": "Shredding",
  "Сортировка": "Sorting",
  "Грануляция": "Granulation",
  "Другое": "Other",

  // ---- Support ----
  "Обращения пользователей": "User requests",
  "Техническая поддержка и консультации": "Technical support and consultations",
  "Новые": "New",
  "Ожидание": "Waiting",
  "Решено": "Resolved",
  "Техническая проблема": "Technical issue",
  "Консультация": "Consultation",
  "Изменение данных": "Data change",
  "Проблемы с доступом": "Access issues",
  "Предложение": "Suggestion",
  "Низкий": "Low",
  "Средний": "Medium",
  "Высокий": "High",
  "Критический": "Critical",
  "Новое": "New",
  "Ожидание ответа": "Awaiting response",
  "Закрыто": "Closed",
  "Переписка": "Conversation",
  "Исполнитель": "Assignee",
  "Взять в работу": "Take on",
  "Изменить статус": "Change status",
  "Информация": "Information",

  // ---- Infrastructure ----
  "Ограждение периметра": "Perimeter fencing",
  "Весовой контроль": "Weight control",
  "Система мониторинга": "Monitoring system",
  "Дренажная система": "Drainage system",
  "Противопожарное оборудование": "Fire safety equipment",
  "Экологический мониторинг": "Environmental monitoring",
  "Мусоровозов": "Garbage trucks",
  "Экскаваторов": "Excavators",
  "Тракторов": "Tractors",
  "Бульдозеров": "Bulldozers",
  "Пищевые отходы": "Food waste",
  "Прочее": "Other",
  "Разрешение на эксплуатацию": "Operating permit",

  // ---- Roles admin page ----
  "Роли и права доступа": "Roles and access permissions",
  "Нет доступа": "No access",
  "Матрица прав доступа": "Access permission matrix",
  "Модуль": "Module",
  "Разрешено": "Allowed",
  "Запрещено": "Denied",
  "Создать роль": "Create role",

  // ---- Regions for filters ----
  "Регион: Все": "Region: All",
  "Статус: Все": "Status: All",
  "Категория: Все": "Category: All",
  "Расчёты: Все": "Calculations: All",
  "Отчётность: Все": "Reporting: All",

  // ---- Hazard classes ----
  "I класс (чрезв. опасные)": "Class I (extremely hazardous)",
  "II класс (высоко опасные)": "Class II (highly hazardous)",
  "III класс (умеренно опасные)": "Class III (moderately hazardous)",
  "IV класс (малоопасные)": "Class IV (low hazard)",
  "V класс (неопасные)": "Class V (non-hazardous)",

  // ---- Common labels ----
  "Контакты": "Contacts",
  "Баланс": "Balance",
  "Оплачено": "Paid",
  "подтверждено": "confirmed",
  "Расчёт": "Calculation",
  "Оплатить": "Pay",
  "Способы оплаты": "Payment methods",
  "Банковская карта": "Bank card",
  "Банковский перевод": "Bank transfer",
  "История операций": "Operations history",
  "Начисления": "Charges",
  "Оплаты": "Payments",
  "Начисление": "Charge",
  "Оплата": "Payment",
  "Корректировка": "Correction",
  "Зачёт": "Offset",
  "Возврат": "Refund",
  "Оплата пени": "Penalty payment",
  "Нет операций": "No operations",
  "Открыть": "Open",

  // ---- Contacts ----
  "Режим работы": "Working hours",
  "Понедельник - Пятница": "Monday - Friday",
  "Суббота": "Saturday",
  "Воскресенье": "Sunday",
  "Выходной": "Day off",
  "Приёмная": "Reception",

  // ---- Strategy ----
  "Стратегия и миссия": "Strategy and mission",

  // ---- Documents section ----
  "Нормативные документы": "Regulatory documents",
  "Постановление №322": "Decree No. 322",
  "Постановление №730": "Decree No. 730",
  "Постановление №563": "Decree No. 563",
  "Постановление №561": "Decree No. 561",

  // ---- Economics ----
  "Экономические аспекты": "Economic aspects",
  "создание и развитие инфраструктуры переработки": "creation and development of recycling infrastructure",
  "поддержку перерабатывающих предприятий": "support for recycling enterprises",
  "внедрение инновационных технологий": "introduction of innovative technologies",
  "образовательные и социальные проекты": "educational and social projects",
  "повышение эффективности отрасли": "improving industry efficiency",

  // ---- Features ----
  "Основные направления деятельности": "Main areas of activity",
  "Администрирование утилизационного сбора": "Recycling fee administration",
  "Развитие инфраструктуры обращения с отходами": "Waste management infrastructure development",
  "Повышение уровня переработки": "Improving recycling rates",
  "Экологическое просвещение": "Environmental education",
  "Мониторинг и контроль эффективности": "Monitoring and efficiency control",

  // ---- Account store ----
  "Начисление утилизационного сбора": "Recycling fee charge",
  "Оплата утилизационного сбора": "Recycling fee payment",
  "Начисление пени за просрочку оплаты": "Late payment penalty charge",
  "Оплата пени за просрочку": "Late payment penalty payment",

  // ---- Product groups (ecoPayments) ----
  "Изделия из гофрированной бумаги/картона": "Corrugated paper/cardboard products",
  "Изделия из негофрированной бумаги/картона": "Non-corrugated paper/cardboard products",
  "Масла": "Oils",
  "Шины, покрышки и камеры резиновые": "Tires, casings and rubber tubes",
  "Изделия из резины (за исключением шин)": "Rubber products (excluding tires)",
  "Изделия пластмассовые упаковочные": "Plastic packaging products",
  "Изделия пластмассовые прочие": "Other plastic products",
  "Стекло полое": "Hollow glass",
  "Компьютеры и периферийное оборудование": "Computers and peripherals",
  "Мониторы, приемники телевизионные": "Monitors and TV receivers",
  "Элементы первичные и батареи": "Primary cells and batteries",
  "Аккумуляторы свинцовые": "Lead accumulators",
  "Батареи аккумуляторные": "Rechargeable batteries",
  "Оборудование электрическое осветительное": "Electric lighting equipment",
  "Техника бытовая крупная": "Large household appliances",
  "Техника бытовая мелкая, инструмент": "Small household appliances and tools",
  "Оборудование холодильное и вентиляционное": "Refrigeration and ventilation equipment",
  "Фильтры для ДВС": "ICE filters",
  "Упаковка полимерная (без галогенов)": "Polymer packaging (halogen-free)",
  "Упаковка полимерная (с галогенами)": "Polymer packaging (with halogens)",
  "Упаковка комбинированная": "Combined packaging",
  "Упаковка из гофрокартона": "Corrugated cardboard packaging",
  "Упаковка из бумаги/картона": "Paper/cardboard packaging",
  "Упаковка стеклянная": "Glass packaging",

  // ---- Norms and rates page ----
  "Бумага и картон": "Paper and cardboard",
  "Масла, шины и резина": "Oils, tires and rubber",
  "Пластмассы и стекло": "Plastics and glass",
  "Электроника и оборудование": "Electronics and equipment",
  "Бытовая техника и фильтры": "Household appliances and filters",
  "Упаковка": "Packaging",
  "сом/тонна": "KGS/ton",
  "текущий": "current",
  "ГРУППА": "GROUP",

  // ---- Various labels used across many pages ----
  "Отчёт не найден": "Report not found",
  "Расчёт не найден": "Calculation not found",
  "Плательщик не найден": "Payer not found",
  "Полигон не найден": "Landfill not found",
  "Декларация не найдена": "Declaration not found",
  "Переработчик не найден": "Recycler not found",
  "Заявка не найдена": "Application not found",
  "Организации не найдены": "Organizations not found",
  "Плательщики не найдены": "Payers not found",
  "Компании не найдены": "Companies not found",
  "Попробуйте изменить параметры поиска": "Try changing search parameters",
  "Попробуйте изменить параметры фильтрации": "Try changing filter parameters",
  "Нет записей": "No records",
  "Данные успешно обновлены": "Data updated successfully",
  "Организация успешно создана": "Organization created successfully",
  "Данные организации обновлены": "Organization data updated",
  "Организация удалена": "Organization deleted",
  "Документ загружен": "Document uploaded",
  "Запись успешно создана": "Record created successfully",
  "Данные обновлены": "Data updated",
  "Запись удалена": "Record deleted",
  "Все периоды": "All periods",
  "Все годы": "All years",
  "Все виды отходов": "All waste types",
  "Все виды лицензий": "All license types",
  "Все категории": "All categories",
  "Все приоритеты": "All priorities",
  "Все каналы": "All channels",
  "Ещё фильтры": "More filters",
  "год": "year",
  "Страница": "Page",
  "Показывать": "Show per page",
  "Показаны": "Shown",
  "обращений": "tickets",
  "плательщиков": "payers",
  "Введите ответ...": "Enter reply...",
  "Загрузить": "Upload",
  "Скачать": "Download",
  "Нет документов": "No documents",
  "Нет комментариев": "No comments",
  "Добавить комментарий": "Add comment",
  "Добавить комментарий...": "Add comment...",
  "Видны только сотрудникам МПРЭТН": "Visible only to MNRE employees",
  "Комментарии сотрудников": "Employee comments",
  "Документы не прикреплены": "No documents attached",
  "Файл слишком большой": "File too large",
  "Недопустимый формат": "Invalid format",
  "Допустимые форматы: PDF, JPG, PNG": "Allowed formats: PDF, JPG, PNG",
  "Максимальный размер файла: 10 МБ": "Maximum file size: 10 MB",
  "Максимальный размер: 10 МБ": "Maximum size: 10 MB",
  "Б": "B",
  "КБ": "KB",
  "МБ": "MB",
  "Черновик сохранён": "Draft saved",
  "Расчёт отправлен на проверку": "Calculation submitted for review",
  "Максимум 10 файлов": "Maximum 10 files",
  "Предпросмотр": "Preview",
  "Отчёты": "Reports",
  "Системные настройки": "System settings",
  "Сессии": "Sessions",
  "Расчёт утильсбора": "Recycling fee calculation",
  "Пункты приёма": "Reception points",
  "всего": "total",
  "Нет платежей": "No payments",
  "Нет деклараций": "No declarations",
  "I квартал": "Q1",
  "II квартал": "Q2",
  "III квартал": "Q3",
  "IV квартал": "Q4",
  "Квартальный отчёт": "Quarterly report",
  "Годовой отчёт": "Annual report",
  "За один квартал": "For one quarter",
  "За весь год": "For the entire year",
  "Шаг": "Step",
  "Период": "Period",
  "Данные": "Data",
  "Проверка": "Review",
  "ОсОО": "LLC",
  "ОАО": "OJSC",
  "ИП": "IE",
  "Прочие": "Other",
  "Органика": "Organic",
  "Переработано": "Recycled",
  "Все категории": "All categories",
  "Пластик": "Plastic",
  "Бумага и картон": "Paper and cardboard",
  "класс": "class",
  "сом/т": "KGS/t",
  "Не найдено": "Not found",
  "Виды отходов не найдены": "Waste types not found",
  "Данные о переработке": "Recycling data",
  "Необязательно": "Optional",
  "Загружен": "Uploaded",
  "Удалить файл": "Delete file",
  "Выбрать файлы": "Choose files",
  "Показать все": "Show all",
  "Отчёт успешно отправлен!": "Report submitted successfully!",
  "Номер отчёта": "Report number",
  "Дата подачи": "Submission date",
  "Вернуться к списку": "Return to list",
  "Декларация одобрена": "Declaration approved",
  "Декларация отклонена": "Declaration rejected",
  "Возвращена на доработку": "Returned for revision",
  "Декларация повторно подана": "Declaration resubmitted",
  "Отчёт создан": "Report created",
  "Отчёт принят": "Report accepted",
  "Отчёт отклонён": "Report rejected",
  "Возвращён на доработку": "Returned for revision",
  "Финансовая сводка": "Financial summary",
  "История деклараций": "Declarations history",
  "История платежей": "Payment history",
  "История изменений": "Change history",
  "Общая информация": "General information",
  "Данные плательщика": "Payer data",
  "от": "from",
  "Тип плательщика": "Payer type",
  "Адрес": "Address",
  "Расчётный период": "Calculation period",
  "Срок оплаты": "Payment deadline",
  "Ввоз": "Import",
  "Дата ввоза": "Import date",
  "Подтверждающие документы": "Supporting documents",
  "Итоги расчёта": "Calculation totals",
  "Сумма утилизационного сбора": "Recycling fee amount",
  "тонн": "tons",
  "Отправить на проверку": "Submit for review",
  "Удаление расчёта": "Calculation deletion",
  "Отозвать расчёт": "Recall calculation",
  "Принять расчёт": "Accept calculation",
  "Принять отчёт": "Accept report",
  "Отклонить отчёт": "Reject report",
  "Одобрить возврат": "Approve refund",
  "Подать повторно": "Resubmit",
  "Допустимые форматы": "Allowed formats",
  "Документ об оплате отправлен": "Payment document sent",
  "Расчёт принят": "Calculation accepted",
  "Генерация PDF будет доступна в следующем обновлении": "PDF generation will be available in the next update",
  "Скачивание файлов будет доступно после подключения хранилища": "File downloads will be available after connecting storage",
  "Экспорт декларации в Excel будет доступен в следующем обновлении": "Declaration export to Excel will be available in the next update",
  "Удалить навсегда": "Delete permanently",

  // ---- Payment methods ----
  "По реквизитам в любом банке": "By payment details at any bank",
  "QR-код": "QR code",
  "Плательщик": "Payer",
  "Скачать платёжное поручение": "Download payment order",
  "Оплатить сейчас": "Pay now",
  "Банковский перевод": "Bank transfer",

  // ---- Eco Waste Types categories ----
  "Пластик": "Plastic",
  "Бумага и картон": "Paper and cardboard",
  "Стекло": "Glass",
  "Металл": "Metal",
  "Органика": "Organic",
  "Приём остановлен": "Reception stopped",

  // ---- Various other exact matches ----
  "Общие настройки": "General settings",
  "Название системы": "System name",
  "Часовой пояс": "Timezone",
  "Описание системы": "System description",
  "Email поддержки": "Support email",
  "Телефон поддержки": "Support phone",
  "Язык интерфейса": "Interface language",
  "Русский": "Russian",
  "Кыргызча": "Kyrgyz",
  "English": "English",
  "Формат даты": "Date format",
  "Валюта": "Currency",
  "Сом (с)": "KGS (c)",
  "Доллар США ($)": "US Dollar ($)",
  "Евро (€)": "Euro (€)",
  "Настройки SMTP": "SMTP settings",
  "SMTP сервер": "SMTP server",
  "Порт": "Port",
  "Имя пользователя": "Username",
  "Имя отправителя": "Sender name",
  "Email отправителя": "Sender email",
  "Использовать TLS": "Use TLS",
  "Тестовое письмо": "Test email",
  "Тестовое письмо отправлено": "Test email sent",
  "Резервное копирование": "Backup",
  "Создать копию": "Create backup",
  "Автоматическое резервное копирование": "Automatic backup",
  "Частота": "Frequency",
  "Каждый час": "Hourly",
  "Ежедневно": "Daily",
  "Еженедельно": "Weekly",
  "Сжатие": "Compression",
  "Авто": "Auto",
  "Вручную": "Manual",
  "Режим обслуживания": "Maintenance mode",
  "Информация о системе": "System information",
  "Аптайм": "Uptime",
  "ОС сервера": "Server OS",
  "Использование диска": "Disk usage",
  "Проверка обновлений...": "Checking for updates...",
  "Текущая версия": "Current version",
  "Доступно обновление": "Update available",
  "Что нового:": "What's new:",
  "Система обновлена": "System is up to date",
  "Просмотр записи": "View record",
  "Создание записи": "Create record",
  "Редактирование": "Editing",
  "Район": "District",
  "Организация": "Organization",
  "Примечания": "Notes",
  "Директор": "Director",
  "Мощность": "Capacity",
  "Лицензия": "License",
  "Срок действия": "Validity period",
  "Годовой объём": "Annual volume",
  "Площадь": "Area",
  "га": "ha",
  "Объём": "Volume",
  "Координаты": "Coordinates",

  // ---- Penalty ----
  "Пеня за просрочку оплаты": "Late payment penalty",
  "Сумма задолженности": "Debt amount",
  "Дней просрочки": "Days overdue",
  "календарных дней": "calendar days",
  "Ставка пени": "Penalty rate",
  "0,09% в день": "0.09% per day",
  "Пеня за 1 день": "Penalty per day",
  "Итого пеня": "Total penalty",
};

// Merge all supplement dictionaries into the main exactDict
Object.assign(exactDict, supplementDict, supplementDict2, supplementDict3, supplementDict4, supplementDict5, supplementDict6, supplementDict7, supplementDict8);

// ============================================================
// 2. PATTERN-BASED TRANSLATIONS (word/phrase replacement)
// ============================================================
const patternTranslations = [
  // Domain-specific terms (order matters - longer patterns first)
  [/утилизационн(?:ый|ого|ому|ым|ом) сбор(?:а|у|ом|е)?/gi, "recycling fee"],
  [/утильсбор(?:а|у|ом|е)?/gi, "recycling fee"],
  [/расширенн(?:ая|ой|ую|ые) ответственност(?:ь|и|ью) производител(?:ей|я)/gi, "Extended Producer Responsibility"],
  [/РОП/g, "EPR"],
  [/ГП\s*[«""]?Эко\s*Оператор[»""]?/gi, "SE \"Eco Operator\""],
  [/ГП Эко Оператор/gi, "SE Eco Operator"],
  [/Эко\s*Оператор/gi, "Eco Operator"],
  [/МПРЭТН\s*КР/g, "MNRE KR"],
  [/МПРЭТН/g, "MNRE"],
  [/переработчик(?:а|ов|ам|ами|ах|у|е|и)?/gi, "recycler(s)"],
  [/плательщик(?:а|ов|ам|ами|ах|у|е|и)?/gi, "payer(s)"],
  [/полигон(?:а|ов|ам|ами|ах|у|е|ы)?(?:\s+ТБО)?/gi, "landfill(s)"],
  [/пен(?:и|ю|ей|ям|ями|ях|я)/gi, "penalty"],
  [/лицевой счёт/gi, "account statement"],
  [/лицевы(?:е|х|м|ми) счет(?:а|ов|ам|ами|ах)/gi, "account statements"],
  [/ТН\s*ВЭД/g, "HS Code"],
  [/ГСКП/g, "SCCP"],
  [/ПКМ\s*КР/g, "GD KR"],
  [/КМ\s*КР/g, "CM KR"],
  [/ЕСИ\s*Түндүк/g, "ESI Tunduk"],
  [/ЕСИ\s*Тундук/g, "ESI Tunduk"],
  [/ЕСИ/g, "ESI"],
  [/Кыргыз(?:ской|стан(?:а)?)\s*Республик(?:и|е|у|ой)/gi, "the Kyrgyz Republic"],
  [/Кыргызстан(?:а)?/gi, "Kyrgyzstan"],
  [/декларац(?:ия|ии|ию|ией|иям|иями|иях)/gi, "declaration(s)"],
  [/нормативы?\s*переработки/gi, "recycling standards"],
  [/нормативы?\s*утилизации/gi, "recycling standards"],
  [/нормативн(?:ый|ая|ое|ые|ого|ой|ому|ых)/gi, "regulatory"],
  [/норматив(?:а|ов|у|ом|е|ы)?/gi, "standard(s)"],
  [/ставк(?:а|и|у|ой|е|ам|ами|ах)/gi, "rate(s)"],
  [/отход(?:а|ов|ам|ами|ах|ы)?/gi, "waste"],
  [/переработк(?:а|и|у|ой|е)/gi, "recycling"],

  // Common Russian words -> English
  [/создан(?:а|о|ы|ие)?/gi, "created"],
  [/отправлен(?:а|о|ы)?/gi, "sent"],
  [/принят(?:а|о|ы)?/gi, "accepted"],
  [/отклонён(?:а|о|ы)?/gi, "rejected"],
  [/отклонен(?:а|о|ы)?/gi, "rejected"],
  [/оплачен(?:а|о|ы)?/gi, "paid"],
  [/подан(?:а|о|ы)?/gi, "submitted"],
  [/загружен(?:а|о|ы)?/gi, "uploaded"],
  [/обновлен(?:а|о|ы)?/gi, "updated"],
  [/удален(?:а|о|ы)?/gi, "deleted"],
  [/сохранен(?:а|о|ы)?/gi, "saved"],
  [/завершён(?:а|о|ы)?/gi, "completed"],
  [/завершен(?:а|о|ы)?/gi, "completed"],

  // UI patterns
  [/Введите\s+/gi, "Enter "],
  [/Выберите\s+/gi, "Select "],
  [/Укажите\s+/gi, "Specify "],
  [/Заполните\s+/gi, "Fill in "],
  [/Поиск по\s+/gi, "Search by "],
  [/Поиск\s+/gi, "Search "],
  [/Нажмите\s+/gi, "Click "],
  [/Перетащите\s+/gi, "Drag "],
  [/Скачать\s+/gi, "Download "],
  [/Загрузить\s+/gi, "Upload "],
  [/Удалить\s+/gi, "Delete "],
  [/Добавить\s+/gi, "Add "],
  [/Просмотреть\s+/gi, "View "],
  [/Редактировать\s+/gi, "Edit "],
  [/Создать\s+/gi, "Create "],
  [/Отправить\s+/gi, "Send "],
  [/Сохранить\s+/gi, "Save "],
  [/Подтвердить\s+/gi, "Confirm "],
  [/Показать\s+/gi, "Show "],
  [/Скрыть\s+/gi, "Hide "],

  // More domain terms
  [/организаци(?:я|и|ю|ей|ям|ями|ях)/gi, "organization(s)"],
  [/лицензи(?:я|и|ю|ей|ям|ями|ях)/gi, "license(s)"],
  [/документ(?:а|ов|ам|ами|ах|ы)?/gi, "document(s)"],
  [/расчёт(?:а|ов|ам|ами|ах|ы)?/gi, "calculation(s)"],
  [/отчёт(?:а|ов|ам|ами|ах|ы)?/gi, "report(s)"],
  [/платёж(?:а|ей|ам|ами|ах|и)?/gi, "payment(s)"],
  [/уведомлени(?:е|я|ю|ем|й|ям|ями|ях)/gi, "notification(s)"],
  [/заявк(?:а|и|у|ой|е|ам|ами|ах)/gi, "application(s)"],
  [/пользовател(?:ь|я|ю|ем|и|ей|ям|ями|ях)/gi, "user(s)"],
  [/период(?:а|ов|у|ом|е|ы)?/gi, "period"],
  [/данные?\s/gi, "data "],
  [/система\b/gi, "system"],
  [/системы?\b/gi, "system"],
  [/подачи?\b/gi, "submission"],
  [/проверк(?:а|и|у|ой|е)/gi, "review"],
  [/доступ(?:а|у|ом|е)?/gi, "access"],
  [/результат(?:а|ов|у|ом|е|ы)?/gi, "result(s)"],
  [/информаци(?:я|и|ю|ей)/gi, "information"],
  [/параметр(?:а|ов|ам|ами|ах|ы)?/gi, "parameter(s)"],
  [/настройк(?:а|и|у|ой|е|ам|ами|ах)/gi, "setting(s)"],
  [/статус(?:а|ов|у|ом|е|ы)?/gi, "status"],
  [/количеств(?:о|а|у|ом|е)/gi, "quantity"],
  [/наименование/gi, "name"],
  [/назначение/gi, "purpose"],
  [/описание/gi, "description"],
  [/адрес(?:а|ов|у|ом|е)?/gi, "address"],
  [/телефон(?:а|ов|у|ом|е)?/gi, "phone"],
  [/номер(?:а|ов|у|ом|е)?/gi, "number"],
  [/дат(?:а|ы|у|ой|е)/gi, "date"],
  [/сумм(?:а|ы|у|ой|е)/gi, "amount"],
  [/масса?\b/gi, "mass"],
  [/объём(?:а|ов|у|ом|е)?/gi, "volume"],
  [/формул(?:а|ы|у|ой|е)/gi, "formula"],
  [/таблиц(?:а|ы|у|ой|е)/gi, "table"],
  [/категори(?:я|и|ю|ей|ям|ями|ях)/gi, "category"],
  [/регион(?:а|ов|у|ом|е|ы)?/gi, "region"],
  [/компани(?:я|и|ю|ей|ям|ями|ях)/gi, "company"],
  [/группы?\b/gi, "group"],
  [/подгруппы?\b/gi, "subgroup"],
  [/процент(?:а|ов|у|ом|е|ы)?/gi, "percent"],
  [/значение/gi, "value"],
  [/изменение/gi, "change"],
];

// ============================================================
// 3. HELPER FUNCTIONS
// ============================================================

let totalStrings = 0;
let translatedStrings = 0;
let untranslatedStrings = [];

function isRussian(str) {
  return /[а-яё]/i.test(str);
}

function translateString(value) {
  totalStrings++;

  // Skip empty strings
  if (!value || value.trim() === '') {
    translatedStrings++;
    return value;
  }

  // If no Russian characters, it's already "translated" (technical, English, etc.)
  if (!isRussian(value)) {
    translatedStrings++;
    return value;
  }

  // 1) Exact match
  if (exactDict[value] !== undefined) {
    translatedStrings++;
    return exactDict[value];
  }

  // 2) Try exact match after trimming
  const trimmed = value.trim();
  if (exactDict[trimmed] !== undefined) {
    translatedStrings++;
    return exactDict[trimmed];
  }

  // 3) Pattern-based translation
  let result = value;
  for (const [pattern, replacement] of patternTranslations) {
    result = result.replace(pattern, replacement);
  }

  // Clean up plural markers from patterns
  result = result.replace(/\(s\)/g, '');

  // If we removed all Russian, consider it translated
  if (!isRussian(result)) {
    translatedStrings++;
    return result;
  }

  // 4) If it's HTML content with Russian, try to translate embedded text
  if (result.includes('<') && result.includes('>')) {
    // HTML - try pattern translations on the text parts
    let htmlResult = result;
    for (const [pattern, replacement] of patternTranslations) {
      htmlResult = htmlResult.replace(pattern, replacement);
    }
    htmlResult = htmlResult.replace(/\(s\)/g, '');
    if (!isRussian(htmlResult)) {
      translatedStrings++;
      return htmlResult;
    }
    // Still has Russian but we did our best with HTML
    untranslatedStrings.push(value.substring(0, 80) + (value.length > 80 ? '...' : ''));
    return htmlResult;
  }

  // Not translated
  untranslatedStrings.push(value.substring(0, 80) + (value.length > 80 ? '...' : ''));
  return result;
}

function translateObject(obj) {
  if (typeof obj === 'string') {
    return translateString(obj);
  }
  if (Array.isArray(obj)) {
    return obj.map(item => translateObject(item));
  }
  if (typeof obj === 'object' && obj !== null) {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = translateObject(value);
    }
    return result;
  }
  return obj;
}

// ============================================================
// 4. MAIN
// ============================================================

console.log('Reading ru.json...');
const ruJson = JSON.parse(readFileSync(INPUT, 'utf-8'));

console.log('Translating...');
const enJson = translateObject(ruJson);

console.log('Writing en.json...');
writeFileSync(OUTPUT, JSON.stringify(enJson, null, 2), 'utf-8');

// ---- Report ----
const coverage = ((translatedStrings / totalStrings) * 100).toFixed(1);
console.log('\n====== Translation Report ======');
console.log(`Total string values:  ${totalStrings}`);
console.log(`Translated:           ${translatedStrings}`);
console.log(`Untranslated:         ${totalStrings - translatedStrings}`);
console.log(`Coverage:             ${coverage}%`);

if (untranslatedStrings.length > 0) {
  console.log(`\nFirst ${Math.min(30, untranslatedStrings.length)} untranslated strings:`);
  untranslatedStrings.slice(0, 30).forEach((s, i) => {
    console.log(`  ${i + 1}. ${s}`);
  });
}

console.log('\nDone! en.json written to:', OUTPUT);
